# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b911c040f45123321a47dfd43291f5befdb05ccc66c63e801ee20a5d10c18575278ab31332d14f477b4519967b9878e9772dca653457d8e368f07df4fba3ed4b

test:
  secret_key_base: fb3d2add6ee25626b560b9f81c5638e661570b3769674b91548887f358b6393ffa27fc5c1de95ee2f71d82cc9f18738e467370a8d16ff0285ed2c82f8485373f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
